-- Copia y pega esto en el SQL Editor de Supabase (menú izquierdo) y dale a RUN

-- 1. Tabla Clasificados
CREATE TABLE IF NOT EXISTS clasificados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nick TEXT NOT NULL,
  desc_text TEXT,
  foto TEXT,
  likes INT DEFAULT 0,
  dislikes INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla Torneos
CREATE TABLE IF NOT EXISTS torneos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  fecha TEXT,
  modalidad TEXT,
  partidos JSONB,
  campeon TEXT,
  creado TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla Registro de Votos (Seguridad por IP)
CREATE TABLE IF NOT EXISTS votes_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Desactivar temporalmente RLS (Row Level Security) para permitir que la API de Next.js
-- haga las operaciones de lectura y escritura fácilmente usando la clave pública (anon key)
ALTER TABLE clasificados DISABLE ROW LEVEL SECURITY;
ALTER TABLE torneos DISABLE ROW LEVEL SECURITY;
ALTER TABLE votes_log DISABLE ROW LEVEL SECURITY;

-- Insertar algunos datos iniciales de prueba (Opcional)
INSERT INTO clasificados (nick, desc_text, likes, dislikes) VALUES 
('ZEZE C. - BRASIL', 'Campeón Torneo #1', 10, 2),
('MARCOSPES - ARSENAL', 'Campeón Torneo #2', 24, 5),
('ROSARINO - INGLATERRA', 'Campeón Torneo #3', 15, 1);
