-- Copia y pega esto en el SQL Editor de Supabase (menú izquierdo) y dale a RUN

-- 1. Tabla Clasificados
CREATE TABLE IF NOT EXISTS clasificados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nick TEXT NOT NULL,
  desc_text TEXT,
  foto TEXT,
  likes INT DEFAULT 0,
  dislikes INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla Torneos
CREATE TABLE IF NOT EXISTS torneos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  fecha TEXT,
  modalidad TEXT,
  partidos JSONB,
  campeon TEXT,
  creado TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla Registro de Votos (Seguridad por IP)
CREATE TABLE IF NOT EXISTS votes_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Row Level Security) para proteger las tablas de accesos no autorizados
ALTER TABLE clasificados ENABLE ROW LEVEL SECURITY;
ALTER TABLE torneos ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes_log ENABLE ROW LEVEL SECURITY;

-- Crear políticas para permitir que la clave pública (anon) lea los datos en el frontend
CREATE POLICY "Permitir lectura pública de clasificados" ON clasificados FOR SELECT TO anon USING (true);
CREATE POLICY "Permitir lectura pública de torneos" ON torneos FOR SELECT TO anon USING (true);

-- Las operaciones de INSERT, UPDATE y DELETE las manejará el servidor Next.js (Server Actions)
-- utilizando la Service Role Key (clave privada que se salta el RLS).

-- Insertar algunos datos iniciales de prueba (Opcional)
INSERT INTO clasificados (nick, desc_text, likes, dislikes) VALUES 
('ZEZE C. - BRASIL', 'Campeón Torneo #1', 10, 2),
('MARCOSPES - ARSENAL', 'Campeón Torneo #2', 24, 5),
('ROSARINO - INGLATERRA', 'Campeón Torneo #3', 15, 1);
