-- ============================================
-- PES6 ARENA — Schema + Migración
-- ============================================

-- 1. Tabla Clasificados (Participantes)
CREATE TABLE IF NOT EXISTS clasificados (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nick TEXT NOT NULL,
  desc_text TEXT,
  foto TEXT,
  equipo TEXT,
  edad TEXT,
  localidad TEXT,
  historia TEXT,
  youtube_links JSONB,
  tipo TEXT DEFAULT 'campeon',
  likes INT DEFAULT 0,
  dislikes INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla Registro de Votos (Seguridad por IP)
CREATE TABLE IF NOT EXISTS votes_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE clasificados ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes_log ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública
CREATE POLICY "Permitir lectura pública de clasificados" ON clasificados FOR SELECT TO anon USING (true);

-- ============================================
-- MIGRACIÓN: Ejecutar si la tabla ya existe
-- ============================================
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS tipo TEXT DEFAULT 'campeon';
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS equipo TEXT;
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS edad TEXT;
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS localidad TEXT;
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS historia TEXT;
-- ALTER TABLE clasificados ADD COLUMN IF NOT EXISTS youtube_links JSONB;
